### PR TITLE
Engine integration

### PR DESCRIPTION
**Pull request by mayork**
branch where engine model integration is being completed

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
Btw, since I am trying to debug some idiosyncrasies of CFP_Fuselage atm, I think we should sit and wait on this pull request a little bit. But feel free to keep developing in the meanwhile; it is nothing that will affect the engine integration.

**Comment by mayork** [comment]
@1ozturkbe the engine isn't involved in the fuselage model at all, right?

**Comment by 1ozturkbe** [comment]
Nope. There is a single constraint that makes sure that the vertical tail is at least 4*engine radius.

**Comment by 1ozturkbe** [comment]
If you have a lot of trouble getting it to work, I would recommend updating CFP until the latest commit 50f1b47. It is a lot more... stable than the previous commits :P

**Comment by 1ozturkbe** [comment]
I found a bug. In  StateLinking model, you have two for loops, one for linking climb, and one for linking cruise segments. But they are both labeled climb. That should help?

**Comment by mayork** [comment]
ah good catch. didn't make a difference here since the two values were equal but certainly was a bug.

I think i'll try and update to the new CFP...although it might be best if we do that together tomorrow by just doing a merge deconflict. what time are you free?

**Comment by 1ozturkbe** [comment]
I am free from 10-3. Let me know when you can make it. Also, just to whet your appetite: 
d8

**Comment by mayork** [comment]
that looks awesome! and okay i'll shoot you a text around 10 and come over

**Comment by mayork** [comment]
@1ozturkbe what i'm going to do is move all the engine integration stuff into the newest commit, but then we should both start working off of that one

**Comment by 1ozturkbe** [comment]
Btw, should we close this issue at this point? It seems moot.

**Comment by mayork** [comment]
yep this is done

**Pull request closed without merging**
