### PR TITLE
TASOPT flight profile

### PR DESCRIPTION
**Pull request by mayork**
upgrading the aircraft model to the TASOPT flight profile for validation purposes

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
Cool! Can you outline the main differences between this flight profile and the simple one? Because it seems that this also has 2 climb and cruise segments. 
Furthermore, numeng is still set to 1 from when we were debugging the fuel consumption errors. Perhaps that should be changed. 
Also, just curious, why are you constraining Mach number in the cruise segments?

**Comment by mayork** [comment]
it's not done yet, hence some of the things you mentioned.

This will include reserve fuel descent and the tasopt cruise climb with constant mach and CL

**Comment by 1ozturkbe** [comment]
Ok cool. Will merge!

**Comment by 1ozturkbe** [comment]
Feel free to keep working on the branch or to delete it Martin .

**Comment by mayork** [comment]
i'm going ot keep working on it....wasn't supposed to be merged yet since it's not done

**Comment by bqpd** [comment]
Also looks like it broke tests above, so I might have to remove you guys from unit testing...

**Comment by mayork** [comment]
do all the PRs get tested or just master? this branch wasn't supposed to be merged so if only master is  tested Berk should just undo the merge

**Comment by 1ozturkbe** [comment]
I don't understand why this is being tested... The only files within TESTS are CFP_Fuselage_Performance.py and CFP_Fuselage_Performance_int_9e5793.py, which shouldn't raise any issues. @bqpd should I revert?

**Comment by bqpd** [comment]
Or you could do what @whoburg and I do, and flag PRs that are ready to be merged with `@reviewer, ready for review`

**Comment by bqpd** [comment]
All PRs are tested! :D I don't know why this one is failling, but it does look like it might be a jenkins issue...paging @galbramc  while I dig in

**Comment by 1ozturkbe** [comment]
K, whatever floats your boat!

**Pull request merged**
