### PR TITLE
Revert "TASOPT flight profile"

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Reverts hoburg/d8#13. TASOPT flight profile not yet ready.

### CODE REVIEW

**Comment by galbramc** [comment]
@whoburg, can we white list @1ozturkbe?

**Comment by whoburg** [comment]
add to whitelist

**Comment by whoburg** [comment]
@galbramc, that's a jenkins setting as opposed to a github setting, correct?

**Comment by galbramc** [comment]
Yes the white list a jenkins setting, and it's repo specific. So if you have one person you want white listed on many different repos, you have to white list them on each repo.

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by mayork** [comment]
@1ozturkbe I'm getting an interesting result that the aircraft actually does not want to perform a cruise climb, it'd like to fly at a constant altitude

**Comment by 1ozturkbe** [comment]
@mayork did you check subs? We sub CruiseAlt = 30000 in the substitutions.

**Comment by mayork** [comment]
yeah i actually semi-abandonded this and switched to the engine repo because I wanted the engine model so the right pressures were applied...when the engine is included cruise altitude can be left as a free variable (which I am doing)

**Comment by 1ozturkbe** [comment]
So you are saying that, for the engine model with a basic aircraft, the aircraft wants to fly at a constant altitude... What is the altitude, just curious?

**Comment by mayork** [comment]
altitude depends on mission range and if the mach number is fixed to be 0.8 or not....anyways, it varies from approx 31,000-39,500 or so. Very reasonable answers.

**Comment by 1ozturkbe** [comment]
Well then I'm happy.

**Pull request closed without merging**
