### PR TITLE
Merging genVSP

### PR DESCRIPTION
**Pull request by 1ozturkbe**
@mayork I want to merge genVSP into master, but it seems like there are some inconsistent constraints within multimission.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
Firstly:
```python
        if not multimission:
               constraints.extend([
                    aircraft['n_{pax}'] == 180.,
                    ReqRng == 3000.*units('nmi'),
                    ])
```
This constraint is going to be badly behaved if we sweep n_{pax}.

**Comment by mayork** [comment]
i'm not sure how to sub a vector into a vector variable hence we can't use subs and multimission together

**Comment by 1ozturkbe** [comment]
That's really poopy and inconvenient. Perhaps I will hold off for a little bit... Does multimission now work with the near-optimal fix? Perhaps then it is better to integrate the updated cruise climb constraints.

**Comment by mayork** [comment]
Nah it keeps crashing my python, not sure why. Try integrating the new cruise climb first

**Comment by mayork** [comment]
Nah it keeps crashing my python, not sure why. Try integrating the new cruise climb first

**Comment by 1ozturkbe** [comment]
Here's what I'm gonna do. I'm going to add cruiseclimb2 to genVSP. I'm going to confirm it works as expected. Then I'm going to add it to master by hand as well, because I don't want to deal with a gajillion merge conflicts. And it should work like a charm.

**Comment by 1ozturkbe** [comment]
Also, hell yeah, Ned's new code totally works with near optimals!

**Comment by 1ozturkbe** [comment]
@mayork cruise climb works like butter! All altitude constraints are tight, and although we get a few NEAR_OPTIMALs, it successfully hops over them. You could probably integrate the constraints yourself to get multimission working (I don't want to pull master right now because group meeting...) Look at commits  47d95ad1 and dd9419d9 under genVSP. Should be really straightforward!

**Comment by 1ozturkbe** [comment]
I'm going to close this and actually merge the final genVSP, which has the appropriate cruise climb constraints.

**Pull request closed without merging**
